### ISSUE TITLE
Roadmap for Official Plugins

### ISSUE THREAD

**Issue by boywithkeyboard** [boywithkeyboard-archive/cheetah1#20]
**cheetah v0.4.0 introduced support for plugins.**

The following should be offered officially:

- [ ] `cache` (Deno.KV, Redis, Cache API)
- [x] `helmet` (ported from [here](https://github.com/helmetjs/helmet)) #22 
- [ ] `ratelimit` (in-memory, Redis, Deno.KV, Cloudflare Durable Objects)

*Please leave a comment below if you are planning to contribute so we can avoid duplicate work.*

**Comment by boywithkeyboard** [comment]
The cache option will get an upgrade soon, and rate limiting should be implemented on a per-app basis, making this issue obsolete.
