### ISSUE TITLE
Roadmap for v1.0

### ISSUE THREAD

**Issue by boywithkeyboard** [boywithkeyboard-archive/cheetah1#24]
- [ ] Built-in support for tRPC (#13)
- [x] Replace `medleyjs/router` with a custom router #29
- [x] Option to extend context
- [x] Parse headers without deep validation  (refer to [dae083f](https://github.com/azurystudio/cheetah/commit/dae083ffe840a392945336a8184e33da22bc81e2))
- [ ] Improve the build script
     - [ ] Pre-compile pathname to regex
     - [ ] Remove if-else logic for plugins if none are used

**Comment by boywithkeyboard** [comment]
There won't be a v1 version in the foreseeable future. cheetah is as stable as frameworks like Hono and can confidently be used in production.
