### ISSUE TITLE
Roadmap for v0.11.0

### ISSUE THREAD

**Issue by boywithkeyboard** [boywithkeyboard-archive/cheetah1#43]
- [x] deprecate `cache.duration` option #46
- ~~enhance internal routing~~ (delayed to v1.0 due to breaking changes)
- [x] add per-collection cache/cors options #50
- [x] implement automatic HEAD responses #49
- [x] add `runtime` option to build script #47
- ~~publish new guide~~ (will be released separately this week)
