### ISSUE TITLE
Roadmap for v1.0

### ISSUE THREAD

**Issue by boywithkeyboard** [boywithkeyboard-archive/cheetah1#53]
This issue is meant as both a roadmap and note regarding the upcoming v1.0 release.

### Roadmap

- [x] reimagine the plugins api #77 
- ~implement documentation generation~ (part of v1.1)
- ~introduce custom api client~ (will be a standalone module)
- [x] ~major~ performance enhancements
- [x] implement gzip compression using [foras](https://github.com/hazae41/foras) (not necessary for cloudflare workers or deno deploy) #79 
- [x] support basic jsx rendering #96 
- [x] standardize `c.env` across runtimes #85 

### Canceled

- ~allow extending the fetch context~

### Breaking Changes

- #66 
- #72 
- #73 
& more
