### ISSUE TITLE
Roadmap for v1.1

### ISSUE THREAD

**Issue by boywithkeyboard** [boywithkeyboard-archive/cheetah1#87]
### Roadmap

- ~deprecate `c.req.blob()`, `c.req.buffer()`, `c.req.formData()` (extend body validation: `z.instanceof(Blob)` etc.)~ (delayed due to insufficient support by zod)
- ~add `etag` extension~ (delayed to v1.2)
- [x] add `favicon` extension (respond to `/favicon.ico` requests) #126
- [x] add `pretty` extension (pretty-print json) #123 
- [x] move `transform` option to `c.req.body()` method #118 

\+ other unscheduled revisions:
- #120
